# If not provided, the current project's folder name is used (default)
# project_dir = "hello-world"

# Will be created if missing, must be writeable by the executing user
#
# The project folder will be copied into it:
# - project_dir:    wargo
# - dest_base_dir:  /tmp
# - result:         /tmp/wargo
#
# default: ~/tmp (user home dir + tmp)
dest_base_dir = "~/tmp"

# Before each call clean the destination (remove whole project).
#
# default: false
clean = false

# Include .git folder in copy, off by default.
# Enable if you want/need .git related data during compilation.
#
# !!!
# If enabled it will always clean the .git folder in the destination on every run,
# because git creates read-only files, which we cannot overwrite once created.
#
# default: false
include_git = false

# Include target folder in copy, off by default.
# Enable if you have a good reason for it;
# … if you found one, please tell me ;-)
#
# default: false
include_target = false
