name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4.1.1

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - uses: Swatinem/rust-cache@v2.7.1

    - run: cargo fetch
    - run: cargo check --all
    - run: cargo build --all
    - run: cargo test --all

  check_fmt_and_docs:
    name: Checking fmt, clippy, and docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2.7.1

    - run: cargo check --all
    - run: cargo clippy --tests -- -D warnings
    - run: cargo fmt --all -- --check
    - run: cargo doc --no-deps
